"""Initial schema

Revision ID: 5db0fcecc632
Revises: 
Create Date: 2026-01-26 16:16:29.585932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5db0fcecc632'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('HierarchyNode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['HierarchyNode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('NodeImage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['HierarchyNode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('NodeImage')
    op.drop_table('HierarchyNode')
    # ### end Alembic commands ###
